Enables dry-run's client/server/none options with backwards compat
go-vela/vela-kubernetes pull request #139
Opened 2022-12-21 22:17 UTC by colindean

kubectl allows options [client|server|none] instead of just a boolean, starting at some version I'm not sure of. This enables that behavior with a fallback to if the user has passed true or false so folks don't need to update their configurations.

I've mapped true->client and false->none but otherwise treating the parameter as a string.

2023-01-26 20:59 UTC, colindean commented
This getting kinda annoying the Vela logs:

```
WARNING: version difference between client (1.24) and server (1.21) exceeds the supported minor version skew of +/-1
$ /bin/kubectl --kubeconfig=/root/.kube/config apply --dry-run=false --filename=k8s/myproject/training_pvc.yaml
W0126 20:50:13.520375      22 helpers.go:653] --dry-run=false is deprecated (boolean value) and can be replaced with --dry-run=none.
persistentvolumeclaim/myteam--myproject--training--output unchanged
$ /bin/kubectl --kubeconfig=/root/.kube/config apply --dry-run=false --filename=k8s/anotherproject/training_pvc.yaml
W0126 20:50:14.763196      41 helpers.go:653] --dry-run=false is deprecated (boolean value) and can be replaced with --dry-run=none.
persistentvolumeclaim/myteam--anotherproject--training--output unchanged
$ /bin/kubectl --kubeconfig=/root/.kube/config apply --dry-run=false --filename=k8s/anotherproject/training_configmap.yaml
W0126 20:50:15.177479      59 helpers.go:653] --dry-run=false is deprecated (boolean value) and can be replaced with --dry-run=none.
configmap/myteam--anotherproject--training--config unchanged
$ /bin/kubectl --kubeconfig=/root/.kube/config apply --dry-run=false --filename=k8s/anotherproject/tag-and-deploy_configmap.yaml
W0126 20:50:15.588353      78 helpers.go:653] --dry-run=false is deprecated (boolean value) and can be replaced with --dry-run=none.
configmap/myteam--anotherproject--tag-and-deploy--config created
```

Can this PR get merged and released?

2023-03-30 17:20 UTC, plyr4 requested changes

2023-03-30 17:20 UTC, plyr4 commented on cmd/vela-kubernetes/apply_test.go
> +			fmt.Sprintf("--dry-run=none"),
```suggestion
			"--dry-run=none",
```

2023-03-30 17:20 UTC, plyr4 commented on cmd/vela-kubernetes/apply_test.go
> +			fmt.Sprintf("--dry-run=client"),
```suggestion
			"--dry-run=client",
```

2023-03-30 17:20 UTC, plyr4 commented on cmd/vela-kubernetes/apply.go
> +			dryRunOpt = a.DryRun
```suggestion
		dryRunOpt := a.DryRun

		switch a.DryRun {
		case "true":
			dryRunOpt = "client"
		case "false":
			dryRunOpt = "none"
```

2023-03-30 17:21 UTC, plyr4 commented
hey @colindean sorry to review this so late, but it looks great to me, thank you

there are a couple tiny linter issues that can be resolved pretty easy so i left some suggestion comments. 
once we get those i can approve :)

2023-03-30 21:23 UTC, plyr4 commented
lgtm, ty! :D

2023-03-31 18:40 UTC, wass3rw3rk approved these changes

2023-03-31 18:40 UTC, merged